// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwk5q-XW1IurD-YLizfpULaQNdUivZQ0Y',
    appId: '1:697404048095:web:cc41682dd826aff6f4df6a',
    messagingSenderId: '697404048095',
    projectId: 'groupie-81781',
    authDomain: 'groupie-81781.firebaseapp.com',
    storageBucket: 'groupie-81781.appspot.com',
    measurementId: 'G-CEHPMCRH46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi9pA8io9SIfIkxOyBqEinFRyOmBXTuPc',
    appId: '1:697404048095:android:fdd3d439cfe3740ff4df6a',
    messagingSenderId: '697404048095',
    projectId: 'groupie-81781',
    storageBucket: 'groupie-81781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yqnMxD4DSYOHE2k0prXmgJIBCJZrDTQ',
    appId: '1:697404048095:ios:2a98bf50317713eaf4df6a',
    messagingSenderId: '697404048095',
    projectId: 'groupie-81781',
    storageBucket: 'groupie-81781.appspot.com',
    iosBundleId: 'com.example.groupie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yqnMxD4DSYOHE2k0prXmgJIBCJZrDTQ',
    appId: '1:697404048095:ios:71ffa8f70bd2cdcef4df6a',
    messagingSenderId: '697404048095',
    projectId: 'groupie-81781',
    storageBucket: 'groupie-81781.appspot.com',
    iosBundleId: 'com.example.groupie.RunnerTests',
  );
}
